image: add man pages + demangle(1)
oxidecomputer/helios pull request #140
Opened 2024-02-17 05:25 UTC by bcantrill

Also fixes #112.

2024-02-18 14:51 UTC, citrus-it commented
`demangle`, absolutely, yes please.

Adding man pages and related tools to the gimlet ramdisk image feels like a step in the wrong direction, and may also not insignificantly increase zone installation time. Some 13s of instance startup is already due to omicron1 installation time and this may well add a second or two. @smklein and I have been talking about ways to reduce this but in general I'd suggest avoiding increases to the OS image size that can be avoided. Development illumos machines like atrium have the man pages and the common illumos ones are at https://illumos.org/man/

```
# time zoneadm -z test install

real    0m13.571s
user    0m0.325s
sys     0m4.551s
```

2024-02-18 14:59 UTC, citrus-it requested changes

2024-02-18 14:59 UTC, citrus-it commented on image/templates/include/recovery-elide.json
> +        { "t": "remove_files", "file": "/usr/bin/amd64/ar" },
This is a duplicate that will cause the image build to fail. Should it have been `usr/bin/amd64/dump`?

2024-02-18 14:59 UTC, citrus-it commented on image/templates/include/recovery-elide.json
> +        { "t": "remove_files", "file": "/usr/bin/lex" },
I'd consider dropping some of these from the main image too - `lex`, `yacc`, `rpcgen` perhaps?

2024-02-18 14:59 UTC, citrus-it commented on image/templates/include/recovery-elide.json
>          { "t": "remove_files", "dir": "/usr/gcc/7" },
Also:
- usr/bin/apropos
- usr/bin/catman
- usr/bin/man
- usr/bin/mandoc
- usr/bin/whatis
- usr/lib/makewhatis

(the artefacts from `system/man`)

2024-02-18 16:39 UTC, jclulow commented on image/templates/include/recovery-elide.json
>          { "t": "remove_files", "dir": "/usr/gcc/7" },
I think rather than elide them from recovery we could just not install system/man at all in recovery.  We'd just have to move that to a separate package install step that was conditional on `without: recovery` or whatever.  Same with the doc facets.

2024-02-18 17:39 UTC, jclulow commented on image/templates/include/recovery-elide.json
>          { "t": "remove_files", "dir": "/usr/gcc/7" },
FYI: I have pushed 748b0f2b8842590cb19b12e3e4209c94f43963bc to the branch with a suggestion for how this could look.  I haven't tested it, though.

2024-02-18 17:45 UTC, jclulow commented
> Some 13s of instance startup is already due to omicron1 installation time and this may well add a second or two. @smklein and I have been talking about ways to reduce this but in general I'd suggest avoiding increases to the OS image size that can be avoided.
> 
> ```
> # time zoneadm -z test install
> 
> real    0m13.571s
> user    0m0.325s
> sys     0m4.551s
> ```

Is there a bug open that covers this problem?  I agree that that's a relatively long time, and it's definitely longer than I would expect; e.g., on my work system (not a Gimlet):

```
 $ pfexec ptime -m zoneadm -z alpha install
INFO: omicron: installing zone alpha @ "/data/zones/alpha"...
INFO: omicron: replicating /usr tree...
INFO: omicron: replicating /lib tree...
INFO: omicron: replicating /sbin tree...
INFO: omicron: pruning SMF manifests...
INFO: omicron: pruning global-only files...
INFO: omicron: unpacking baseline archive...
INFO: omicron: copying /etc/default/init...
INFO: omicron: install complete, probably!

real        4.461508981
user        0.613072922
sys         3.843153670
trap        0.000023530
tflt        0.000000000
dflt        0.000000000
kflt        0.000000000
lock        0.000000000
slp         4.435181625
lat         0.002651174
stop        0.000388355
```

If we can get a ticket open that describes the problem and where it happens we can start the usual profiling and performance investigation.

2024-02-18 20:02 UTC, jclulow commented
> > Is there a bug open that covers this problem?
> 
> [oxidecomputer/omicron#3682](https://github.com/oxidecomputer/omicron/issues/3682)

Ah ha!  I have attempted to improve things in https://github.com/oxidecomputer/helios-omicron-brand/pull/12 and it's now a bit faster:

```
gimlet-sn07 # zoneadm -z test uninstall -F ; ptime -m zoneadm -z test install
...
INFO: omicron: replicated /usr: 9514 files, 121518507, bytes, 562 msec
...
INFO: omicron: install complete, probably!

real        0.945731000
user        0.409957787
sys         3.937423102
...
```

I'll try and get that landed this week.

2024-02-19 20:10 UTC, citrus-it approved these changes

2024-02-19 20:41 UTC, jclulow approved these changes
Looks much cleaner!  Pleased to see it go faster also haha

2024-02-19 20:43 UTC, merged