Tune zfs parameters for improved IO performance
oxidecomputer/helios pull request #170
Opened 2024-08-12 21:44 UTC by faithanalog

We tune three zfs parameters:

- zfs:zfs_vdev_aggregation_limit - disable
- zfs:zfs_sync_taskq_batch_pct   - reduce to 5%
- zfs:zio_taskq_batch_pct        - reduce to 5%

Like previous zfs tuning, these are about bringing zfs parameters in line with the reality of a modern system like the gimlet, away from defaults that were good on a system with few CPU threads and high-latency spinning disks.

For crucible with a 4k rand write workload, we see an 18% reduction in CPU usage and a 15% increase in throughput. We see no significant change to our 4k rand read or our 4k sequential workloads.

The crucible 4k rand write workload is the most pathological workload we have for zfs on the rack today. Therefore, I do not expect this change to have a negative impact on cockroach/clickhouse (if anything, it might help them out). I have not verified this experimentally.

I built a helios image with this change and booted it on a bench gimlet. I confirmed that the parameters have been changed as we expect:

```
EVT22200004 # mdb -ke 'zfs_vdev_aggregation_limit/D'
zfs_vdev_aggregation_limit:
zfs_vdev_aggregation_limit:     0
EVT22200004 # mdb -ke 'zfs_sync_taskq_batch_pct/D'
zfs_sync_taskq_batch_pct:
zfs_sync_taskq_batch_pct:       5
EVT22200004 # mdb -ke 'zio_taskq_batch_pct/D'
zio_taskq_batch_pct:
zio_taskq_batch_pct:            5
```

2024-08-12 21:49 UTC, jclulow reviewed
> Therefore, I do not expect this change to have a negative impact on cockroach/clickhouse (if anything, it might help them out). I have not verified this experimentally.

I think, in general, we definitely want to look at all the other known I/O workloads we have before we make a change like this.

2024-08-12 21:49 UTC, jclulow commented on image/templates/files/gimlet-system-zfs:dbuf
> +set zfs:zfs_vdev_aggregation_limit = 0
Should we be doing this automatically for all pools that are on non-rotational media?

2024-08-12 21:49 UTC, jclulow commented on image/templates/files/gimlet-system-zfs:dbuf
> +set zfs:zio_taskq_batch_pct = 5
I would like to summon @arekinath to look at this, as I believe he is looking at the same thing.

2024-08-12 21:50 UTC, mkeeter commented on image/templates/files/gimlet-system-zfs:dbuf
> +set zfs:zfs_vdev_aggregation_limit = 0
Since the Gimlet has nothing but SSDs, doing this change is an easy global fix, but OpenZFS _does_ include separate aggregation limit for non-rotational media:
https://github.com/openzfs/zfs/commit/1af240f3b51c080376bb6ae1efc13d62b087b65d

2024-08-12 21:58 UTC, faithanalog commented on image/templates/files/gimlet-system-zfs:dbuf
> +set zfs:zfs_vdev_aggregation_limit = 0
openzfs created a separate tuneable for non-rotational media, and defaults it to 128KiB ( https://github.com/openzfs/zfs/commit/1af240f3b51c080376bb6ae1efc13d62b087b65d )

We went to 0 because we have enterprise SSDs that can serve significantly more IOPS than we are currently capable of sending it under random write conditions right now. I expect that whether or not turning aggregation off is good depends on how good your SSD is at random IO, and more consumer grade SSDs such as you might find in a homelab may not be as thrilled by this. Or maybe they would! It would deserve some testing.

2024-08-12 22:01 UTC, faithanalog commented
> > Therefore, I do not expect this change to have a negative impact on cockroach/clickhouse (if anything, it might help them out). I have not verified this experimentally.
> 
> I think, in general, we definitely want to look at all the other known I/O workloads we have before we make a change like this.

I think cockroach in particular would be nice to benchmark. I think we have some people who know how to do that.

2024-08-12 22:31 UTC, arekinath commented on image/templates/files/gimlet-system-zfs:dbuf
> +set zfs:zio_taskq_batch_pct = 5
So, I can get some more of the reasoning for this together later (but I'm in +10 UTC so it's likely you'll be done for the day before I have time), but:

I would like to see this compared to making the dp_sync_taskq into a TASKQ_DYNAMIC taskq with #ncpus threads, even on very wide boxen.

Dynamic taskqs don't have a single large mutex: they have a lock per hash bucket, but it comes at the cost of the fact that if all their threads are busy then new dispatches are placed on a single "fallback" serial queue. So you really want them sized such that you never use the fallback.

Since there are always #ncpus hash buckets in a dynamic taskq, you ideally want at least that many threads in it. They won't sit there thundering a mutex so if the extra threads are unused it's not such a big deal.

I've been looking at this in relation to some of our workloads where we find that with how long it takes the spa_sync thread (the sole producer for this taskq) to produce new work vs how fast the individual sync tasks are against SSDs, that the actual required concurrency is on the order of 64-256, which I assume is why this was set to 75% of ncpus. But it changes dramatically with workload and is often severely multi-modal

We really want spa_sync to generate writes as fast and as widely as it possibly can to saturate the SSDs. Adding latency to spa_sync has lots of knock-on consequences across the whole system (e.g. induces new read latency elsewhere or holds locks that block userland even with async io) so I think limiting its concurrency because taskq sucks is not a great long-term answer. We should fix taskq, but TASKQ_DYNAMIC might be a bandaid for now. Worth a try anyway (we have it configured like this at UQ)

2024-08-12 22:38 UTC, jclulow commented on image/templates/files/gimlet-system-zfs:dbuf
> +set zfs:zio_taskq_batch_pct = 5
There is also [15993 task queue backlog efficiency](https://www.illumos.org/issues/15993) which feels like it is in this area.  I think it's essentially through code review, but we may need to push and/or help with testing to get it integrated.

2024-08-13 00:44 UTC, faithanalog commented on image/templates/files/gimlet-system-zfs:dbuf
> +set zfs:zio_taskq_batch_pct = 5
> Dynamic taskqs don't have a single large mutex: they have a lock per hash bucket, but it comes at the cost of the fact that if all their threads are busy then new dispatches are placed on a single "fallback" serial queue. So you really want them sized such that you never use the fallback.
> 
> Since there are always #ncpus hash buckets in a dynamic taskq, you ideally want at least that many threads in it. They won't sit there thundering a mutex so if the extra threads are unused it's not such a big deal.

this is very interesting and I definitely want to try it. Is this something I can set with a parameter or will I need to modify the zfs code for it?

2024-08-13 00:50 UTC, faithanalog commented on image/templates/files/gimlet-system-zfs:dbuf
> +set zfs:zio_taskq_batch_pct = 5
also, so you have some additional context on the pathological workload we've been looking at, we have around 48 processes (give or take a few) on a box with cpu 128 threads and 10 disks. it works out so that each disk has 4 or 5 processes, each with a thousand or so files, hammering it constantly with 4k random writes across their files. and this generates astronomical lock contention, like the box is spending 50% of its cpu cycles on spinning on locks and nothing else. these tuneables as i set in the PR help but do not fully resolve it.

2024-09-27 20:34 UTC, jclulow commented
To return to this, I wanted to make sure it was clear that I wasn't looking for a deep new performance investigation, so much as a few smoke tests just to make sure that we're not going to have to revert it inside of a week.  If you can get the change tested on **london** or **madrid** it seems fine to proceed.

I have filed two follow-up issues so that we don't lose track of things:

- oxidecomputer/stlouis#622 to cover future work on the taskq bit, which I believe is important
- [16813 large zfs_vdev_aggregation_limit does not make sense for SSDs](https://www.illumos.org/issues/16813) for the rotational vs SSD aggregation thing

2024-09-27 21:39 UTC, faithanalog commented
Anything in particular you're looking for as that testing goes?

the VM load testing was already done on london/madrid. As API goes, that also exercises the control plane to the extent that my script is not very smart and frequently queries the IPs of 64 VMs with 64 parallel API requests, though it's not going out of its way to load down the API. the API is always a bit sluggish during the crucible load test, about equally so before and after this change. which I have been chalking up to system cpu/network load so far

2024-09-27 21:44 UTC, faithanalog commented
half-serious: We could default rackletteadm to always apply these tuneables to everyone's workload and see if anyone complains

2024-09-27 21:51 UTC, jclulow commented
No I think that sounds like enough testing.  If it was not great under load to begin with and it's still not great now, though I think that's worth another ticket somewhere else, it seems fine to move forward.

2024-09-27 21:56 UTC, jclulow requested changes
comment style consistency nits, then good to go!

2024-09-27 21:56 UTC, jclulow commented on image/templates/files/gimlet-system-zfs:dbuf
> +* We set the limit to 0 disable aggregation entirely.
```suggestion
*
* By default, ZFS tries to internally aggregate multiple I/O operations, so it
* can dispatch them as a single operation to the disk.  This logic comes from
* the era of spinning drives, where putting in the work to issue fewer, larger
* commands would increase throughput.  For SSDs, and especially the Gimlet
* SSDs, it instead generates extra work within ZFS that reduces throughput.
*
* We set the limit to 0 disable aggregation entirely.
*
```

2024-09-27 21:56 UTC, jclulow commented on image/templates/files/gimlet-system-zfs:dbuf
> +* worker threads.
```suggestion
*
* These task queues will allocate threads equal to 75% of the number of CPU
* threads on the system.  On the Gimlet, that means that it allocates 96
* threads.  These queues are per-zpool, so actually that means it allocates 960
* threads by default.  This is a bit excessive.  These parameters bring it down
* to allocate 5% per pool instead, significantly reducing mutex contention
* between the worker threads.
*
```

2024-10-07 17:55 UTC, jclulow approved these changes

2024-10-07 17:56 UTC, merged